SOURCES={
'nyfed':('New York Fed Markets Data','https://markets.newyorkfed.org/static/docs/markets-api.html','business_daily','official'),
'fred':('Federal Reserve Economic Data','https://fred.stlouisfed.org/','weekly / policy','official'),
'treasury':('U.S. Treasury FiscalData','https://fiscaldata.treasury.gov/api-documentation/','business_daily','official'),
'cboe':('Cboe Global Markets','https://www.cboe.com/tradable-products/vix/term-structure','daily','public_vendor'),
'cftc':('CFTC Commitments of Traders','https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm','weekly','official'),
'finra':('FINRA Margin Statistics','https://www.finra.org/rules-guidance/key-topics/margin-accounts/margin-statistics','monthly','official'),
'sec':('SEC EDGAR','https://www.sec.gov/search-filings/edgar-application-programming-interfaces','quarterly','official')}
CORE={
'sofr':('SOFR','percent','nyfed'),'iorb':('IORB','percent','fred'),'sofr_iorb_spread':('SOFR−IORB 利差','bp','nyfed'),'effr':('EFFR','percent','nyfed'),'obfr':('OBFR','percent','nyfed'),'tgcr':('TGCR','percent','nyfed'),'bgcr':('BGCR','percent','nyfed'),'tga_daily':('TGA closing balance','USD bn','treasury'),'on_rrp':('ON RRP 使用量','USD bn','nyfed'),'srf_usage':('SRF 使用量','USD bn','nyfed'),'reserve_balances':('Reserve Balances','USD bn','fred'),'fed_total_assets':('Fed Total Assets','USD bn','fred'),'tga_weekly_h41':('TGA weekly cross-check','USD bn','fred')}
OPTIONAL={'vix_curve':('VIX term structure','index','cboe','missing'),'crypto_funding_btc':('BTC perpetual funding','percent','cboe','missing'),'cta_proxy':('CTA positioning proxy','z-score','cftc','missing'),'cross_asset_corr':('Cross-asset correlation','coefficient','cftc','missing'),'gamma_flip':('Gamma flip level','index','cboe','paid_data_unavailable'),'spx_0dte_share':('SPX 0DTE share','percent','cboe','paid_data_unavailable'),'put_call_skew':('Put/call skew','index','cboe','paid_data_unavailable'),'finra_margin_debt':('FINRA margin debt','USD bn','finra','missing'),'sp500_top10_weight':('S&P 500 Top-10 weight','percent','cboe','manual_update_due'),'buffett_indicator_proxy':('Buffett indicator proxy','percent','fred','missing'),'m2_vs_nasdaq':('M2 vs Nasdaq divergence','z-score','fred','missing'),'insider_ratio_proxy':('Insider buy/sell proxy','ratio','sec','missing'),'ndx_forward_pe':('NDX forward P/E','multiple','cboe','paid_data_unavailable'),'hyperscaler_capex':('Hyperscaler aggregate CapEx','USD bn','sec','missing'),'capex_acceleration':('CapEx YoY acceleration','pp','sec','missing'),'upstream_backlog':('AI upstream backlog','USD bn','sec','manual_update_due'),'prepayments':('Customer prepayments','USD bn','sec','manual_update_due'),'take_or_pay':('Take-or-pay commitments','USD bn','sec','manual_update_due')}
def knowledge(mid):
 common={'question_answered':'呢個指標所屬層面有冇出現壓力或轉折？','why_track':'同獨立訊號一齊使用，辨識流動性、放大器或基本面變化。','interpretation_up':'上升方向要按指標定義及 regime 判讀。','interpretation_down':'下降方向要配合趨勢及其他確認。','false_positives':'發布時間、樣本組成、技術日及定義轉變都可能造成假訊號。','confirm_with':'價格、存量／流量及 backstop 等獨立 evidence blocks。','cannot_conclude':'唔可以靠單一指標證明危機、泡沫爆破或資產價格方向。'}
 if mid=='sofr_iorb_spread':common.update(question_answered='Treasury repo 現金融資相對 IORB 是否變得昂貴？',why_track='監測邊際 secured-funding pressure。',false_positives='月尾、季尾、Treasury settlement、collateral specials 或 dealer window dressing。',confirm_with='EFFR−IORB、TGCR／BGCR、Reserve Balances 及 SRF。',cannot_conclude='唔可以單獨證明準備金短缺、金融危機或股市即將下跌。')
 return common
def manifest():
 out=[]
 for mid,(label,unit,sid) in CORE.items():
  q=knowledge(mid);out.append({'id':mid,'label':label,'unit':unit,'frequency':SOURCES[sid][2],'layer':'liquidity_fuel','role':'primary' if mid in ('sofr_iorb_spread','reserve_balances','srf_usage') else 'driver','quality':'derived_official' if 'spread' in mid else 'official','availability':'automatic','methodology':'官方發布值；衍生利差以 (rate − IORB) × 100 bp。' if 'spread' in mid else '官方來源標準化；缺失保留 null。','source_url':SOURCES[sid][1],'series_path':f'data/series/{mid}.json',**q})
 for mid,(label,unit,sid,status) in OPTIONAL.items():
  out.append({'id':mid,'label':label,'unit':unit,'frequency':SOURCES[sid][2],'layer':'market_ignition' if mid in list(OPTIONAL)[:7] else 'fundamental_exit','role':'guardrail','quality':'paid_required' if status=='paid_data_unavailable' else 'proxy','availability':status,'methodology':'尚未有可合法自動重發布嘅資料；明確保留 availability state。','source_url':SOURCES[sid][1],'series_path':f'data/series/{mid}.json',**knowledge(mid)})
 return out
